auto:         false
permalink:    /blog/:title
pygments:     true
paginate:     4
exclude:
  - Rakefile

title:        Pollinimini.net
utl:          http://pollinimini.net
feed:         /atom.xml
description:  DrSlump @ Pollinimini.net

author:
  name:       Iván -DrSlump- Montes
  email:      drslump@pollinimini.net
  twitter:    drslump

disqus:
  id:         pollinimini

nav:
  - name: Blog
    url:  /
  - name: About
    url:  /about/
    subnav:
      - name: Portfolio
        url: /portfolio/
      - name: Contact
        url: mailto:drslump-at-pollinimini-dot-net

about:
  - >
    Content is licensed under
    <a href="http://creativecommons.org/licenses/by/2.5/">Creative Commons Attribution 2.5</a>
    unless stated otherwise.
  - >
    The opinions of authors expressed herein are those of the author and do not
    necessarily state or reflect those of the site owner.

copyright:
  - "&copy; Copyright 2004-2010 Iván -DrSlump- Montes"
  - >
    Design based on <a href="http://dezinerfolio.com/demo/darkelegance">Dark Elegance</a>
    by <a href="http://dezinerfolio.com">Dezinerfolio</a>
  - Published with <a href="http://jekyllrb.com">Jekyll</a>

css:
  - /resources/global.css

js:
  - http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js

